# Database
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.0.3:3306/trips?serverTimezone=UTC&characterEncoding=UTF-8
    username: thankryu
    password: dkzkdnsxm8!
  # Jpa 설정
  jpa:
    hibernate:
        ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 2000

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    operations-sorter: method
    path: /swagger-ui
  paths-to-match: /**
  show-login-endpoint: true
  cache:
    disabled: true

logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace